name: Mirror to EXOPA-OAPa

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Test PAT
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN_EXOPA }}
        run: |
          echo "Testing PAT access..."
          git ls-remote \
            "https://x-access-token:${MIRROR_TOKEN}@github.com/EXOPA-OAPa/PHOTO-CAT.git"
